name: Android CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: List Files
      run: find .


    - name: Upload debug APK
      uses: actions/upload-artifact@v3.1.0
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Upload release (unsigned) APK
      uses: actions/upload-artifact@v3.1.0
      with:
        name: app-release-unsigned.apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Publish artifacts with Gradle
      run: ./gradlew publishToMavenLocal

    - name: List Files in m2
      run: find ~/.m2

    - name: Upload m2 androidLib AAR
      uses: actions/upload-artifact@v3.1.0
      with:
        name: pumpx2-android.aar
        path: ~/.m2/repository/com/jwoglom/pumpx2/pumpx2-android/*/pumpx2-android-[0-9.]*.aar

    - name: Upload m2 androidLib source JAR
      uses: actions/upload-artifact@v3.1.0
      with:
        name: pumpx2-android-sources.jar
        path: ~/.m2/repository/com/jwoglom/pumpx2/pumpx2-android/*/pumpx2-android-[0-9.]*-sources.jar

    - name: Upload m2 messages JAR
      uses: actions/upload-artifact@v3.1.0
      with:
        name: pumpx2-messages.jar
        path: ~/.m2/repository/com/jwoglom/pumpx2/pumpx2-messages/*/pumpx2-messages-[0-9.]*.jar

    - name: Upload m2 shared JAR
      uses: actions/upload-artifact@v3.1.0
      with:
        name: pumpx2-shared.jar
        path: ~/.m2/repository/com/jwoglom/pumpx2/pumpx2-shared/*/pumpx2-shared-[0-9.]*.jar

    - name: Upload m2 messages fat JAR
      uses: actions/upload-artifact@v3.1.0
      with:
        name: pumpx2-messages-all.jar
        path: ~/.m2/repository/com/jwoglom/pumpx2/pumpx2-messages/*/pumpx2-messages-[0-9.]*-all.jar

    - name: Upload m2 messages source JAR
      uses: actions/upload-artifact@v3.1.0
      with:
        name: pumpx2-messages-sources.jar
        path: ~/.m2/repository/com/jwoglom/pumpx2/pumpx2-messages/*/pumpx2-messages-[0-9.]*-sources.jar

    - name: Upload m2 cliparser fat JAR
      uses: actions/upload-artifact@v3.1.0
      with:
        name: pumpx2-cliparser-all.jar
        path: ~/.m2/repository/com/jwoglom/pumpx2/pumpx2-cliparser/*/pumpx2-cliparser-[0-9.]*-all.jar

    - name: Upload generated m2 repository
      uses: actions/upload-artifact@v3.1.0
      with:
        name: maven-repository.zip
        path: |
          ~/.m2/repository/

    - name: Unit Test
      run: ./gradlew testDebugUnitTest

    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }} # IMPORTANT: run Android Test Report regardless

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b


#    - name: Import GPG key
#      id: import_gpg
#      uses: crazy-max/ghaction-import-gpg@v5
#      with:
#        gpg_private_key: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
#        passphrase: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
#    - name: Run Gradle Publish
#      env:
#        ORG_GRADLE_PROJECT_SIGNINGKEY: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
#        ORG_GRADLE_PROJECT_SIGNINGKEYID: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
#        ORG_GRADLE_PROJECT_SIGNINGPASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
#        ORG_GRADLE_PROJECT_SONATYPEUSERNAME: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEUSERNAME }}
#        ORG_GRADLE_PROJECT_SONATYPEPASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPEPASSWORD }}
#      run: |
#        ./gradlew publish -PsigningKeyId="$ORG_GRADLE_PROJECT_SIGNINGKEYID" -PsigningKeyPassword="$ORG_GRADLE_PROJECT_SIGNINGPASSWORD" -PsonatypeUsername="$ORG_GRADLE_PROJECT_SONATYPEUSERNAME" -PsonatypePassword="$ORG_GRADLE_PROJECT_SONATYPEPASSWORD"
